package com.techstomach.justdental.model.schema;
// Generated Nov 19, 2016 4:08:03 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AllergyDb generated by hbm2java
 */
@Entity
@Table(name = "allergy_db", catalog = "jd_database")
public class AllergyDb implements java.io.Serializable {

	private Integer allergyId;
	private String name;
	private boolean isActive;
	private List<PatientAllergyDb> patientAllergyDbs;

	public AllergyDb() {
	}

	public AllergyDb(boolean isActive) {
		this.isActive = isActive;
	}

	public AllergyDb(String name, boolean isActive, List<PatientAllergyDb>  patientAllergyDbs) {
		this.name = name;
		this.isActive = isActive;
		this.patientAllergyDbs = patientAllergyDbs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AllergyID", unique = true, nullable = false)
	public Integer getAllergyId() {
		return this.allergyId;
	}

	public void setAllergyId(Integer allergyId) {
		this.allergyId = allergyId;
	}

	@Column(name = "Name", length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "IsActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "allergyDb")
	public List<PatientAllergyDb>  getPatientAllergyDbs() {
		return this.patientAllergyDbs;
	}

	public void setPatientAllergyDbs(List<PatientAllergyDb>  patientAllergyDbs) {
		this.patientAllergyDbs = patientAllergyDbs;
	}

}
