package com.techstomach.justdental.model.schema;
// Generated Jan 4, 2017 9:42:35 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.Vector;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppUsers generated by hbm2java
 */
@Entity
@Table(name = "App_Users")
public class AppUsers implements java.io.Serializable {

	private Integer userId;
	private String firstName;
	private String middleName;
	private String lastName;
	private String userName;
	private String password;
	private String emailAddress;
	private String phoneNumber;
	private String licenseNumber;
	private String applicationName;
	private String passwordQuestion;
	private Date dateCreated;
	private Date dateModified;
	private int modifiedBy;
	private Date lastLogin;
	private Date lastPasswordChanged;
	private int isActive;
	private int numberOfLogins;
	private String qualification;
	private String passwordAnswer;
	//private Vector<UserRole> userRoles = new Vector<UserRole>();
	//private Vector<Clinicdoctor> clinicdoctors = new Vector<Clinicdoctor>();

	public AppUsers() {
	}

	public AppUsers(String firstName, String lastName, String userName, String password, String emailAddress,
			String phoneNumber, String applicationName, String passwordQuestion, Date dateCreated, Date dateModified,
			int modifiedBy, int isActive, int numberOfLogins) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.userName = userName;
		this.password = password;
		this.emailAddress = emailAddress;
		this.phoneNumber = phoneNumber;
		this.applicationName = applicationName;
		this.passwordQuestion = passwordQuestion;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
		this.modifiedBy = modifiedBy;
		this.isActive = isActive;
		this.numberOfLogins = numberOfLogins;
	}

//	public AppUsers(String firstName, String middleName, String lastName, String userName, String password,
//			String emailAddress, String phoneNumber, String licenseNumber, String applicationName,
//			String passwordQuestion, Date dateCreated, Date dateModified, int modifiedBy, Date lastLogin,
//			Date lastPasswordChanged, int isActive, int numberOfLogins, String qualification, String passwordAnswer,
//					Vector<UserRole> userRoles, Vector<Clinicdoctor> clinicdoctors) {
//		this.firstName = firstName;
//		this.middleName = middleName;
//		this.lastName = lastName;
//		this.userName = userName;
//		this.password = password;
//		this.emailAddress = emailAddress;
//		this.phoneNumber = phoneNumber;
//		this.licenseNumber = licenseNumber;
//		this.applicationName = applicationName;
//		this.passwordQuestion = passwordQuestion;
//		this.dateCreated = dateCreated;
//		this.dateModified = dateModified;
//		this.modifiedBy = modifiedBy;
//		this.lastLogin = lastLogin;
//		this.lastPasswordChanged = lastPasswordChanged;
//		this.isActive = isActive;
//		this.numberOfLogins = numberOfLogins;
//		this.qualification = qualification;
//		this.passwordAnswer = passwordAnswer;
//		this.userRoles = userRoles;
//		this.clinicdoctors = clinicdoctors;
//	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "UserID", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "FirstName", nullable = false)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "MiddleName")
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "LastName", nullable = false)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "UserName", nullable = false)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "Password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "EmailAddress", nullable = false)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "PhoneNumber", nullable = false)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "LicenseNumber")
	public String getLicenseNumber() {
		return this.licenseNumber;
	}

	public void setLicenseNumber(String licenseNumber) {
		this.licenseNumber = licenseNumber;
	}

	@Column(name = "ApplicationName", nullable = false)
	public String getApplicationName() {
		return this.applicationName;
	}

	public void setApplicationName(String applicationName) {
		this.applicationName = applicationName;
	}

	@Column(name = "PasswordQuestion", nullable = false)
	public String getPasswordQuestion() {
		return this.passwordQuestion;
	}

	public void setPasswordQuestion(String passwordQuestion) {
		this.passwordQuestion = passwordQuestion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreated", nullable = false, length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateModified", nullable = false, length = 19)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	@Column(name = "ModifiedBy", nullable = false)
	public int getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(int modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastLogin", length = 19)
	public Date getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastPasswordChanged", length = 19)
	public Date getLastPasswordChanged() {
		return this.lastPasswordChanged;
	}

	public void setLastPasswordChanged(Date lastPasswordChanged) {
		this.lastPasswordChanged = lastPasswordChanged;
	}

	@Column(name = "IsActive", nullable = false)
	public int getIsActive() {
		return this.isActive;
	}

	public void setIsActive(int isActive) {
		this.isActive = isActive;
	}

	@Column(name = "NumberOfLogins", nullable = false)
	public int getNumberOfLogins() {
		return this.numberOfLogins;
	}

	public void setNumberOfLogins(int numberOfLogins) {
		this.numberOfLogins = numberOfLogins;
	}

	@Column(name = "Qualification")
	public String getQualification() {
		return this.qualification;
	}

	public void setQualification(String qualification) {
		this.qualification = qualification;
	}

	@Column(name = "PasswordAnswer")
	public String getPasswordAnswer() {
		return this.passwordAnswer;
	}

	public void setPasswordAnswer(String passwordAnswer) {
		this.passwordAnswer = passwordAnswer;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appUsers")
//	public Vector<UserRole> getUserRoles() {
//		return this.userRoles;
//	}
//
//	public void setUserRoles(Vector<UserRole> userRoles) {
//		this.userRoles = userRoles;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appUsers")
//	public Vector<Clinicdoctor> getClinicdoctors() {
//		return this.clinicdoctors;
//	}
//
//	public void setClinicdoctors(Vector<Clinicdoctor> clinicdoctors) {
//		this.clinicdoctors = clinicdoctors;
//	}

}
