package com.techstomach.justdental.model.schema;
// Generated Jan 4, 2017 9:42:35 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AuditClinic generated by hbm2java
 */
@Entity
@Table(name = "Audit_Clinic")
public class AuditClinic implements java.io.Serializable {

	private Integer auditKey;
	private Integer clinicId;
	private String clinicName;
	private String taxNumber;
	private String primaryContactName;
	private String primaryContactNumber;
	private Integer isActive;
	private String street1;
	private String street2;
	private String locality;
	private String city;
	private String state;
	private String country;
	private String gmap;
	private String pincode;
	private String lastAction;
	private String lastModifiedBy;
	private Date lastModifiedDate;

	public AuditClinic() {
	}

	public AuditClinic(Integer clinicId, String clinicName, String taxNumber, String primaryContactName,
			String primaryContactNumber, Integer isActive, String street1, String street2, String locality, String city,
			String state, String country, String gmap, String pincode, String lastAction, String lastModifiedBy,
			Date lastModifiedDate) {
		this.clinicId = clinicId;
		this.clinicName = clinicName;
		this.taxNumber = taxNumber;
		this.primaryContactName = primaryContactName;
		this.primaryContactNumber = primaryContactNumber;
		this.isActive = isActive;
		this.street1 = street1;
		this.street2 = street2;
		this.locality = locality;
		this.city = city;
		this.state = state;
		this.country = country;
		this.gmap = gmap;
		this.pincode = pincode;
		this.lastAction = lastAction;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Audit_Key", unique = true, nullable = false)
	public Integer getAuditKey() {
		return this.auditKey;
	}

	public void setAuditKey(Integer auditKey) {
		this.auditKey = auditKey;
	}

	@Column(name = "ClinicID")
	public Integer getClinicId() {
		return this.clinicId;
	}

	public void setClinicId(Integer clinicId) {
		this.clinicId = clinicId;
	}

	@Column(name = "ClinicName")
	public String getClinicName() {
		return this.clinicName;
	}

	public void setClinicName(String clinicName) {
		this.clinicName = clinicName;
	}

	@Column(name = "TaxNumber")
	public String getTaxNumber() {
		return this.taxNumber;
	}

	public void setTaxNumber(String taxNumber) {
		this.taxNumber = taxNumber;
	}

	@Column(name = "PrimaryContactName")
	public String getPrimaryContactName() {
		return this.primaryContactName;
	}

	public void setPrimaryContactName(String primaryContactName) {
		this.primaryContactName = primaryContactName;
	}

	@Column(name = "PrimaryContactNumber")
	public String getPrimaryContactNumber() {
		return this.primaryContactNumber;
	}

	public void setPrimaryContactNumber(String primaryContactNumber) {
		this.primaryContactNumber = primaryContactNumber;
	}

	@Column(name = "IsActive")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@Column(name = "Street1")
	public String getStreet1() {
		return this.street1;
	}

	public void setStreet1(String street1) {
		this.street1 = street1;
	}

	@Column(name = "Street2")
	public String getStreet2() {
		return this.street2;
	}

	public void setStreet2(String street2) {
		this.street2 = street2;
	}

	@Column(name = "Locality")
	public String getLocality() {
		return this.locality;
	}

	public void setLocality(String locality) {
		this.locality = locality;
	}

	@Column(name = "City")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "State")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "Country")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "GMAP")
	public String getGmap() {
		return this.gmap;
	}

	public void setGmap(String gmap) {
		this.gmap = gmap;
	}

	@Column(name = "Pincode")
	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	@Column(name = "Last_Action")
	public String getLastAction() {
		return this.lastAction;
	}

	public void setLastAction(String lastAction) {
		this.lastAction = lastAction;
	}

	@Column(name = "Last_Modified_by")
	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Last_Modified_date", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
