package com.techstomach.justdental.model.schema;
// Generated Jan 4, 2017 9:42:35 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AuditRole generated by hbm2java
 */
@Entity
@Table(name = "Audit_Role")
public class AuditRole implements java.io.Serializable {

	private Integer auditKey;
	private Integer roleId;
	private String name;
	private String description;
	private String lastAction;

	public AuditRole() {
	}

	public AuditRole(Integer roleId, String name, String description, String lastAction) {
		this.roleId = roleId;
		this.name = name;
		this.description = description;
		this.lastAction = lastAction;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Audit_Key", unique = true, nullable = false)
	public Integer getAuditKey() {
		return this.auditKey;
	}

	public void setAuditKey(Integer auditKey) {
		this.auditKey = auditKey;
	}

	@Column(name = "RoleID")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "Name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Last_Action")
	public String getLastAction() {
		return this.lastAction;
	}

	public void setLastAction(String lastAction) {
		this.lastAction = lastAction;
	}

}
