package com.techstomach.justdental.model.schema;
// Generated Jan 4, 2017 9:42:35 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AuditAppUsers generated by hbm2java
 */
@Entity
@Table(name = "Audit_App_Users")
public class AuditAppUsers implements java.io.Serializable {

	private Integer auditKey;
	private Integer userId;
	private String firstName;
	private String middleName;
	private String lastName;
	private String userName;
	private String password;
	private String emailAddress;
	private String phoneNumber;
	private String licenseNumber;
	private String applicationName;
	private String passwordQuestion;
	private Date dateCreated;
	private Date dateModified;
	private Integer modifiedBy;
	private Date lastLogin;
	private Date lastPasswordChanged;
	private Integer isActive;
	private Integer numberOfLogins;
	private String qualification;
	private String passwordAnswer;
	private String lastAction;

	public AuditAppUsers() {
	}

	public AuditAppUsers(Integer userId, String firstName, String middleName, String lastName, String userName,
			String password, String emailAddress, String phoneNumber, String licenseNumber, String applicationName,
			String passwordQuestion, Date dateCreated, Date dateModified, Integer modifiedBy, Date lastLogin,
			Date lastPasswordChanged, Integer isActive, Integer numberOfLogins, String qualification,
			String passwordAnswer, String lastAction) {
		this.userId = userId;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.userName = userName;
		this.password = password;
		this.emailAddress = emailAddress;
		this.phoneNumber = phoneNumber;
		this.licenseNumber = licenseNumber;
		this.applicationName = applicationName;
		this.passwordQuestion = passwordQuestion;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
		this.modifiedBy = modifiedBy;
		this.lastLogin = lastLogin;
		this.lastPasswordChanged = lastPasswordChanged;
		this.isActive = isActive;
		this.numberOfLogins = numberOfLogins;
		this.qualification = qualification;
		this.passwordAnswer = passwordAnswer;
		this.lastAction = lastAction;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Audit_key", unique = true, nullable = false)
	public Integer getAuditKey() {
		return this.auditKey;
	}

	public void setAuditKey(Integer auditKey) {
		this.auditKey = auditKey;
	}

	@Column(name = "UserID")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "FirstName")
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "MiddleName")
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "LastName")
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "UserName")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "Password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "EmailAddress")
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "PhoneNumber")
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "LicenseNumber")
	public String getLicenseNumber() {
		return this.licenseNumber;
	}

	public void setLicenseNumber(String licenseNumber) {
		this.licenseNumber = licenseNumber;
	}

	@Column(name = "ApplicationName")
	public String getApplicationName() {
		return this.applicationName;
	}

	public void setApplicationName(String applicationName) {
		this.applicationName = applicationName;
	}

	@Column(name = "PasswordQuestion")
	public String getPasswordQuestion() {
		return this.passwordQuestion;
	}

	public void setPasswordQuestion(String passwordQuestion) {
		this.passwordQuestion = passwordQuestion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreated", length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateModified", length = 19)
	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	@Column(name = "ModifiedBy")
	public Integer getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Integer modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastLogin", length = 19)
	public Date getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastPasswordChanged", length = 19)
	public Date getLastPasswordChanged() {
		return this.lastPasswordChanged;
	}

	public void setLastPasswordChanged(Date lastPasswordChanged) {
		this.lastPasswordChanged = lastPasswordChanged;
	}

	@Column(name = "IsActive")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@Column(name = "NumberOfLogins")
	public Integer getNumberOfLogins() {
		return this.numberOfLogins;
	}

	public void setNumberOfLogins(Integer numberOfLogins) {
		this.numberOfLogins = numberOfLogins;
	}

	@Column(name = "Qualification")
	public String getQualification() {
		return this.qualification;
	}

	public void setQualification(String qualification) {
		this.qualification = qualification;
	}

	@Column(name = "PasswordAnswer")
	public String getPasswordAnswer() {
		return this.passwordAnswer;
	}

	public void setPasswordAnswer(String passwordAnswer) {
		this.passwordAnswer = passwordAnswer;
	}

	@Column(name = "Last_Action")
	public String getLastAction() {
		return this.lastAction;
	}

	public void setLastAction(String lastAction) {
		this.lastAction = lastAction;
	}

}
