package com.techstomach.justdental.model.schema;
// Generated Nov 19, 2016 4:08:03 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CalendarDb generated by hbm2java
 */
@Entity
@Table(name = "calendar_db", catalog = "jd_database")
public class CalendarDb implements java.io.Serializable {

	private Integer calendarId;
	private Date fromDateTime;
	private Date toDateTime;
	private String status;
	private Integer doctorId;
	private Integer patientId;
	private Integer clinicId;
	private Integer bookingId;

	public CalendarDb() {
	}

	public CalendarDb(Date fromDateTime, Date toDateTime, String status, Integer doctorId, Integer patientId,
			Integer clinicId, Integer bookingId) {
		this.fromDateTime = fromDateTime;
		this.toDateTime = toDateTime;
		this.status = status;
		this.doctorId = doctorId;
		this.patientId = patientId;
		this.clinicId = clinicId;
		this.bookingId = bookingId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CalendarId", unique = true, nullable = false)
	public Integer getCalendarId() {
		return this.calendarId;
	}

	public void setCalendarId(Integer calendarId) {
		this.calendarId = calendarId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FromDateTime", length = 19)
	public Date getFromDateTime() {
		return this.fromDateTime;
	}

	public void setFromDateTime(Date fromDateTime) {
		this.fromDateTime = fromDateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ToDateTime", length = 19)
	public Date getToDateTime() {
		return this.toDateTime;
	}

	public void setToDateTime(Date toDateTime) {
		this.toDateTime = toDateTime;
	}

	@Column(name = "Status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "DoctorId")
	public Integer getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(Integer doctorId) {
		this.doctorId = doctorId;
	}

	@Column(name = "PatientId")
	public Integer getPatientId() {
		return this.patientId;
	}

	public void setPatientId(Integer patientId) {
		this.patientId = patientId;
	}

	@Column(name = "ClinicId")
	public Integer getClinicId() {
		return this.clinicId;
	}

	public void setClinicId(Integer clinicId) {
		this.clinicId = clinicId;
	}

	@Column(name = "BookingId")
	public Integer getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(Integer bookingId) {
		this.bookingId = bookingId;
	}

}
