package com.techstomach.justdental.model.schema;
// Generated Nov 19, 2016 4:08:03 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CategoryDb generated by hbm2java
 */
@Entity
@Table(name = "category_db", catalog = "jd_database")
public class CategoryDb implements java.io.Serializable {

	private Integer categoryId;
	private String name;
	private String description;
	private Date dateCreated;
	private boolean isActive;
	private List<ProductDb> productDbs;

	public CategoryDb() {
	}

	public CategoryDb(String name, Date dateCreated, boolean isActive) {
		this.name = name;
		this.dateCreated = dateCreated;
		this.isActive = isActive;
	}

	public CategoryDb(String name, String description, Date dateCreated, boolean isActive, List<ProductDb> productDbs) {
		this.name = name;
		this.description = description;
		this.dateCreated = dateCreated;
		this.isActive = isActive;
		this.productDbs = productDbs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CategoryID", unique = true, nullable = false)
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "Name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreated", nullable = false, length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "IsActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoryDb")
	public List<ProductDb> getProductDbs() {
		return this.productDbs;
	}

	public void setProductDbs(List<ProductDb> productDbs) {
		this.productDbs = productDbs;
	}

}
