package com.techstomach.justdental.model.schema;
// Generated Jan 4, 2017 9:42:35 AM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import java.util.Vector;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clinic generated by hbm2java
 */
@Entity
@Table(name = "Clinic")
public class Clinic implements java.io.Serializable {

	private Integer clinicId;
	private String clinicName;
	private String taxNumber;
	private String primaryContactName;
	private String primaryContactNumber;
	private int isActive;
	private String street1;
	private String street2;
	private String locality;
	private String city;
	private String state;
	private String country;
	private String gmap;
	private String pincode;
//	private Vector<Clinicdoctor> clinicdoctors = new Vector<Clinicdoctor>();

	public Clinic() {
	}

	public Clinic(String clinicName, String taxNumber, String primaryContactName, String primaryContactNumber,
			int isActive, String street1, String street2, String locality, String city, String state, String country,
			String gmap, String pincode) {
		this.clinicName = clinicName;
		this.taxNumber = taxNumber;
		this.primaryContactName = primaryContactName;
		this.primaryContactNumber = primaryContactNumber;
		this.isActive = isActive;
		this.street1 = street1;
		this.street2 = street2;
		this.locality = locality;
		this.city = city;
		this.state = state;
		this.country = country;
		this.gmap = gmap;
		this.pincode = pincode;
	}

//	public Clinic(String clinicName, String taxNumber, String primaryContactName, String primaryContactNumber,
//			int isActive, String street1, String street2, String locality, String city, String state, String country,
//			String gmap, String pincode, Vector<Clinicdoctor> clinicdoctors) {
//		this.clinicName = clinicName;
//		this.taxNumber = taxNumber;
//		this.primaryContactName = primaryContactName;
//		this.primaryContactNumber = primaryContactNumber;
//		this.isActive = isActive;
//		this.street1 = street1;
//		this.street2 = street2;
//		this.locality = locality;
//		this.city = city;
//		this.state = state;
//		this.country = country;
//		this.gmap = gmap;
//		this.pincode = pincode;
//		this.clinicdoctors = clinicdoctors;
//	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ClinicID", unique = true, nullable = false)
	public Integer getClinicId() {
		return this.clinicId;
	}

	public void setClinicId(Integer clinicId) {
		this.clinicId = clinicId;
	}

	@Column(name = "ClinicName", nullable = false)
	public String getClinicName() {
		return this.clinicName;
	}

	public void setClinicName(String clinicName) {
		this.clinicName = clinicName;
	}

	@Column(name = "TaxNumber", nullable = false)
	public String getTaxNumber() {
		return this.taxNumber;
	}

	public void setTaxNumber(String taxNumber) {
		this.taxNumber = taxNumber;
	}

	@Column(name = "PrimaryContactName", nullable = false)
	public String getPrimaryContactName() {
		return this.primaryContactName;
	}

	public void setPrimaryContactName(String primaryContactName) {
		this.primaryContactName = primaryContactName;
	}

	@Column(name = "PrimaryContactNumber", nullable = false)
	public String getPrimaryContactNumber() {
		return this.primaryContactNumber;
	}

	public void setPrimaryContactNumber(String primaryContactNumber) {
		this.primaryContactNumber = primaryContactNumber;
	}

	@Column(name = "IsActive", nullable = false)
	public int getIsActive() {
		return this.isActive;
	}

	public void setIsActive(int isActive) {
		this.isActive = isActive;
	}

	@Column(name = "Street1", nullable = false)
	public String getStreet1() {
		return this.street1;
	}

	public void setStreet1(String street1) {
		this.street1 = street1;
	}

	@Column(name = "Street2", nullable = false)
	public String getStreet2() {
		return this.street2;
	}

	public void setStreet2(String street2) {
		this.street2 = street2;
	}

	@Column(name = "Locality", nullable = false)
	public String getLocality() {
		return this.locality;
	}

	public void setLocality(String locality) {
		this.locality = locality;
	}

	@Column(name = "City", nullable = false)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "State", nullable = false)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "Country", nullable = false)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "GMAP", nullable = false)
	public String getGmap() {
		return this.gmap;
	}

	public void setGmap(String gmap) {
		this.gmap = gmap;
	}

	@Column(name = "Pincode", nullable = false)
	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clinic")
//	public Vector<Clinicdoctor> getClinicdoctors() {
//		return this.clinicdoctors;
//	}
//
//	public void setClinicdoctors(Vector<Clinicdoctor> clinicdoctors) {
//		this.clinicdoctors = clinicdoctors;
//	}

}
