package com.techstomach.justdental.model.schema;
// Generated Jan 4, 2017 9:42:35 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClinicservicemapId generated by hbm2java
 */
@Embeddable
public class ClinicservicemapId implements java.io.Serializable {

	private int clinicId;
	private int serviceId;

	public ClinicservicemapId() {
	}

	public ClinicservicemapId(int clinicId, int serviceId) {
		this.clinicId = clinicId;
		this.serviceId = serviceId;
	}

	@Column(name = "ClinicID", nullable = false)
	public int getClinicId() {
		return this.clinicId;
	}

	public void setClinicId(int clinicId) {
		this.clinicId = clinicId;
	}

	@Column(name = "ServiceID", nullable = false)
	public int getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(int serviceId) {
		this.serviceId = serviceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClinicservicemapId))
			return false;
		ClinicservicemapId castOther = (ClinicservicemapId) other;

		return (this.getClinicId() == castOther.getClinicId()) && (this.getServiceId() == castOther.getServiceId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClinicId();
		result = 37 * result + this.getServiceId();
		return result;
	}

}
