package com.techstomach.justdental.model.schema;
// Generated Jan 4, 2017 9:42:35 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Clinicservicemap generated by hbm2java
 */
@Entity
@Table(name = "ClinicServiceMap")
public class Clinicservicemap implements java.io.Serializable {

	private ClinicservicemapId id;

	public Clinicservicemap() {
	}

	public Clinicservicemap(ClinicservicemapId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "clinicId", column = @Column(name = "ClinicID", nullable = false)),
			@AttributeOverride(name = "serviceId", column = @Column(name = "ServiceID", nullable = false)) })
	public ClinicservicemapId getId() {
		return this.id;
	}

	public void setId(ClinicservicemapId id) {
		this.id = id;
	}

}
