package com.techstomach.justdental.model.schema;
// Generated Jan 4, 2017 9:42:35 AM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import java.util.Vector;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clinicdoctor generated by hbm2java
 */
@Entity
@Table(name = "ClinicDoctor")
public class Clinicdoctor implements java.io.Serializable {

	private Integer clinicDoctorId;
	private AppUsers appUsers;
	private Clinic clinic;
	private String daysAvailable;
	private String timeSlots;
//	private Vector<Appointment> appointments = new Vector<Appointment>();

	public Clinicdoctor() {
	}

	public Clinicdoctor(AppUsers appUsers, Clinic clinic, String daysAvailable, String timeSlots) {
		this.appUsers = appUsers;
		this.clinic = clinic;
		this.daysAvailable = daysAvailable;
		this.timeSlots = timeSlots;
	}

//	public Clinicdoctor(AppUsers appUsers, Clinic clinic,
//						String daysAvailable, String timeSlots, Vector<Appointment> appointments) {
//		this.appUsers = appUsers;
//		this.clinic = clinic;
//		this.daysAvailable = daysAvailable;
//		this.timeSlots = timeSlots;
//		this.appointments = appointments;
//	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ClinicDoctorID", unique = true, nullable = false)
	public Integer getClinicDoctorId() {
		return this.clinicDoctorId;
	}

	public void setClinicDoctorId(Integer clinicDoctorId) {
		this.clinicDoctorId = clinicDoctorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID", nullable = false)
	public AppUsers getAppUsers() {
		return this.appUsers;
	}

	public void setAppUsers(AppUsers appUsers) {
		this.appUsers = appUsers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ClinicID", nullable = false)
	public Clinic getClinic() {
		return this.clinic;
	}

	public void setClinic(Clinic clinic) {
		this.clinic = clinic;
	}

	@Column(name = "DaysAvailable", nullable = false)
	public String getDaysAvailable() {
		return this.daysAvailable;
	}

	public void setDaysAvailable(String daysAvailable) {
		this.daysAvailable = daysAvailable;
	}

	@Column(name = "TimeSlots", nullable = false)
	public String getTimeSlots() {
		return this.timeSlots;
	}

	public void setTimeSlots(String timeSlots) {
		this.timeSlots = timeSlots;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clinicdoctor")
//	public Vector<Appointment> getAppointments() {
//		return this.appointments;
//	}
//
//	public void setAppointments(Vector<Appointment> appointments) {
//		this.appointments = appointments;
//	}

}
