package com.techstomach.justdental.model.schema;
// Generated Nov 19, 2016 4:08:03 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FeedchartDb generated by hbm2java
 */
@Entity
@Table(name = "feedchart_db", catalog = "jd_database")
public class FeedchartDb implements java.io.Serializable {

	private Integer feedChartId;
	private PatientCheckinDb patientCheckinDb;
	private Date feedTime;
	private String feedType;
	private String amountOffered;
	private String amountTaken;
	private String vomit;
	private String urine;
	private String stool;
	private String comments;

	public FeedchartDb() {
	}

	public FeedchartDb(PatientCheckinDb patientCheckinDb, Date feedTime) {
		this.patientCheckinDb = patientCheckinDb;
		this.feedTime = feedTime;
	}

	public FeedchartDb(PatientCheckinDb patientCheckinDb, Date feedTime, String feedType, String amountOffered,
			String amountTaken, String vomit, String urine, String stool, String comments) {
		this.patientCheckinDb = patientCheckinDb;
		this.feedTime = feedTime;
		this.feedType = feedType;
		this.amountOffered = amountOffered;
		this.amountTaken = amountTaken;
		this.vomit = vomit;
		this.urine = urine;
		this.stool = stool;
		this.comments = comments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "FeedChartID", unique = true, nullable = false)
	public Integer getFeedChartId() {
		return this.feedChartId;
	}

	public void setFeedChartId(Integer feedChartId) {
		this.feedChartId = feedChartId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PatientCheckInID", nullable = false)
	public PatientCheckinDb getPatientCheckinDb() {
		return this.patientCheckinDb;
	}

	public void setPatientCheckinDb(PatientCheckinDb patientCheckinDb) {
		this.patientCheckinDb = patientCheckinDb;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FeedTime", nullable = false, length = 19)
	public Date getFeedTime() {
		return this.feedTime;
	}

	public void setFeedTime(Date feedTime) {
		this.feedTime = feedTime;
	}

	@Column(name = "FeedType", length = 30)
	public String getFeedType() {
		return this.feedType;
	}

	public void setFeedType(String feedType) {
		this.feedType = feedType;
	}

	@Column(name = "AmountOffered", length = 20)
	public String getAmountOffered() {
		return this.amountOffered;
	}

	public void setAmountOffered(String amountOffered) {
		this.amountOffered = amountOffered;
	}

	@Column(name = "AmountTaken", length = 20)
	public String getAmountTaken() {
		return this.amountTaken;
	}

	public void setAmountTaken(String amountTaken) {
		this.amountTaken = amountTaken;
	}

	@Column(name = "Vomit", length = 20)
	public String getVomit() {
		return this.vomit;
	}

	public void setVomit(String vomit) {
		this.vomit = vomit;
	}

	@Column(name = "Urine", length = 20)
	public String getUrine() {
		return this.urine;
	}

	public void setUrine(String urine) {
		this.urine = urine;
	}

	@Column(name = "Stool", length = 20)
	public String getStool() {
		return this.stool;
	}

	public void setStool(String stool) {
		this.stool = stool;
	}

	@Column(name = "Comments", length = 65535)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
