package com.techstomach.justdental.model.schema;
// Generated Nov 19, 2016 4:08:03 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IntakeChartDb generated by hbm2java
 */
@Entity
@Table(name = "intake_chart_db", catalog = "jd_database")
public class IntakeChartDb implements java.io.Serializable {

	private Integer inTakeChartId;
	private PatientCheckinDb patientCheckinDb;
	private Date chartTime;
	private String kindOfFluid;
	private String amount;

	public IntakeChartDb() {
	}

	public IntakeChartDb(PatientCheckinDb patientCheckinDb, Date chartTime) {
		this.patientCheckinDb = patientCheckinDb;
		this.chartTime = chartTime;
	}

	public IntakeChartDb(PatientCheckinDb patientCheckinDb, Date chartTime, String kindOfFluid, String amount) {
		this.patientCheckinDb = patientCheckinDb;
		this.chartTime = chartTime;
		this.kindOfFluid = kindOfFluid;
		this.amount = amount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "InTakeChartID", unique = true, nullable = false)
	public Integer getInTakeChartId() {
		return this.inTakeChartId;
	}

	public void setInTakeChartId(Integer inTakeChartId) {
		this.inTakeChartId = inTakeChartId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PatientCheckInID", nullable = false)
	public PatientCheckinDb getPatientCheckinDb() {
		return this.patientCheckinDb;
	}

	public void setPatientCheckinDb(PatientCheckinDb patientCheckinDb) {
		this.patientCheckinDb = patientCheckinDb;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ChartTime", nullable = false, length = 19)
	public Date getChartTime() {
		return this.chartTime;
	}

	public void setChartTime(Date chartTime) {
		this.chartTime = chartTime;
	}

	@Column(name = "KindOfFluid", length = 30)
	public String getKindOfFluid() {
		return this.kindOfFluid;
	}

	public void setKindOfFluid(String kindOfFluid) {
		this.kindOfFluid = kindOfFluid;
	}

	@Column(name = "Amount", length = 20)
	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

}
