package com.techstomach.justdental.model.schema;
// Generated Nov 19, 2016 4:08:03 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvoiceDb generated by hbm2java
 */
@Entity
@Table(name = "invoice_db", catalog = "jd_database")
public class InvoiceDb implements java.io.Serializable {

	private Integer invoiceId;
	private BigDecimal total;
	private Date date;
	private boolean isActive;
	private List<InvoiceitemDb> invoiceitemDbs;
	private List<PaymentDb> paymentDbs;

	public InvoiceDb() {
	}

	public InvoiceDb(BigDecimal total, Date date, boolean isActive) {
		this.total = total;
		this.date = date;
		this.isActive = isActive;
	}

	public InvoiceDb(BigDecimal total, Date date, boolean isActive, List<InvoiceitemDb>  invoiceitemDbs, List<PaymentDb> paymentDbs) {
		this.total = total;
		this.date = date;
		this.isActive = isActive;
		this.invoiceitemDbs = invoiceitemDbs;
		this.paymentDbs = paymentDbs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "InvoiceID", unique = true, nullable = false)
	public Integer getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(Integer invoiceId) {
		this.invoiceId = invoiceId;
	}

	@Column(name = "Total", nullable = false, precision = 6)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "IsActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoiceDb")
	public List<InvoiceitemDb>  getInvoiceitemDbs() {
		return this.invoiceitemDbs;
	}

	public void setInvoiceitemDbs(List<InvoiceitemDb>  invoiceitemDbs) {
		this.invoiceitemDbs = invoiceitemDbs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoiceDb")
	public List<PaymentDb> getPaymentDbs() {
		return this.paymentDbs;
	}

	public void setPaymentDbs(List<PaymentDb> paymentDbs) {
		this.paymentDbs = paymentDbs;
	}

}
