package com.techstomach.justdental.model.schema;
// Generated Jan 4, 2017 9:42:35 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvoiceitemId generated by hbm2java
 */
@Embeddable
public class InvoiceitemId implements java.io.Serializable {

	private int invoiceItemId;
	private int invoiceId;

	public InvoiceitemId() {
	}

	public InvoiceitemId(int invoiceItemId, int invoiceId) {
		this.invoiceItemId = invoiceItemId;
		this.invoiceId = invoiceId;
	}

	@Column(name = "InvoiceItemID", nullable = false)
	public int getInvoiceItemId() {
		return this.invoiceItemId;
	}

	public void setInvoiceItemId(int invoiceItemId) {
		this.invoiceItemId = invoiceItemId;
	}

	@Column(name = "InvoiceID", nullable = false)
	public int getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(int invoiceId) {
		this.invoiceId = invoiceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvoiceitemId))
			return false;
		InvoiceitemId castOther = (InvoiceitemId) other;

		return (this.getInvoiceItemId() == castOther.getInvoiceItemId())
				&& (this.getInvoiceId() == castOther.getInvoiceId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getInvoiceItemId();
		result = 37 * result + this.getInvoiceId();
		return result;
	}

}
