package com.techstomach.justdental.model.schema;
// Generated Nov 19, 2016 4:08:03 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InvoiceitemDb generated by hbm2java
 */
@Entity
@Table(name = "invoiceitem_db", catalog = "jd_database")
public class InvoiceitemDb implements java.io.Serializable {

	private Integer invoiceItemId;
	private InvoiceDb invoiceDb;
	private ProductDb productDb;
	private ServiceDb serviceDb;
	private Float quantity;
	private boolean isActive;

	public InvoiceitemDb() {
	}

	public InvoiceitemDb(InvoiceDb invoiceDb, boolean isActive) {
		this.invoiceDb = invoiceDb;
		this.isActive = isActive;
	}

	public InvoiceitemDb(InvoiceDb invoiceDb, ProductDb productDb, ServiceDb serviceDb, Float quantity,
			boolean isActive) {
		this.invoiceDb = invoiceDb;
		this.productDb = productDb;
		this.serviceDb = serviceDb;
		this.quantity = quantity;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "InvoiceItemID", unique = true, nullable = false)
	public Integer getInvoiceItemId() {
		return this.invoiceItemId;
	}

	public void setInvoiceItemId(Integer invoiceItemId) {
		this.invoiceItemId = invoiceItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "InvoiceID", nullable = false)
	public InvoiceDb getInvoiceDb() {
		return this.invoiceDb;
	}

	public void setInvoiceDb(InvoiceDb invoiceDb) {
		this.invoiceDb = invoiceDb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProductID")
	public ProductDb getProductDb() {
		return this.productDb;
	}

	public void setProductDb(ProductDb productDb) {
		this.productDb = productDb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ServiceID")
	public ServiceDb getServiceDb() {
		return this.serviceDb;
	}

	public void setServiceDb(ServiceDb serviceDb) {
		this.serviceDb = serviceDb;
	}

	@Column(name = "Quantity", precision = 12, scale = 0)
	public Float getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Float quantity) {
		this.quantity = quantity;
	}

	@Column(name = "IsActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

}
