package com.techstomach.justdental.model.schema;
// Generated Jan 4, 2017 9:42:35 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.Vector;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name = "invoice")
public class Invoice implements java.io.Serializable {

	private Integer invoiceId;
	private float invoiceAmount;
	private Date paymentDateTime;
	private int patientId;
	private int clinicId;
	private String description;
	private int paymentType;
	private String tax;
	private float totalAmount;
//	private Vector<PatientCheckin> patientCheckins = new Vector<PatientCheckin>();
//	private Vector<Invoiceitem> invoiceitems = new Vector<Invoiceitem>();

	public Invoice() {
	}

	public Invoice(float invoiceAmount, Date paymentDateTime, int patientId, int clinicId, String description,
			int paymentType, String tax, float totalAmount) {
		this.invoiceAmount = invoiceAmount;
		this.paymentDateTime = paymentDateTime;
		this.patientId = patientId;
		this.clinicId = clinicId;
		this.description = description;
		this.paymentType = paymentType;
		this.tax = tax;
		this.totalAmount = totalAmount;
	}

//	public Invoice(float invoiceAmount, Date paymentDateTime, int patientId, int clinicId, String description,
//			int paymentType, String tax, float totalAmount,
//				   Vector<PatientCheckin> patientCheckins, Vector<Invoiceitem> invoiceitems) {
//		this.invoiceAmount = invoiceAmount;
//		this.paymentDateTime = paymentDateTime;
//		this.patientId = patientId;
//		this.clinicId = clinicId;
//		this.description = description;
//		this.paymentType = paymentType;
//		this.tax = tax;
//		this.totalAmount = totalAmount;
//		this.patientCheckins = patientCheckins;
//		this.invoiceitems = invoiceitems;
//	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "InvoiceID", unique = true, nullable = false)
	public Integer getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(Integer invoiceId) {
		this.invoiceId = invoiceId;
	}

	@Column(name = "InvoiceAmount", nullable = false, precision = 14)
	public float getInvoiceAmount() {
		return this.invoiceAmount;
	}

	public void setInvoiceAmount(float invoiceAmount) {
		this.invoiceAmount = invoiceAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PaymentDateTime", nullable = false, length = 19)
	public Date getPaymentDateTime() {
		return this.paymentDateTime;
	}

	public void setPaymentDateTime(Date paymentDateTime) {
		this.paymentDateTime = paymentDateTime;
	}

	@Column(name = "PatientID", nullable = false)
	public int getPatientId() {
		return this.patientId;
	}

	public void setPatientId(int patientId) {
		this.patientId = patientId;
	}

	@Column(name = "ClinicID", nullable = false)
	public int getClinicId() {
		return this.clinicId;
	}

	public void setClinicId(int clinicId) {
		this.clinicId = clinicId;
	}

	@Column(name = "Description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "PaymentType", nullable = false)
	public int getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(int paymentType) {
		this.paymentType = paymentType;
	}

	@Column(name = "Tax", nullable = false)
	public String getTax() {
		return this.tax;
	}

	public void setTax(String tax) {
		this.tax = tax;
	}

	@Column(name = "TotalAmount", nullable = false, precision = 14)
	public float getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(float totalAmount) {
		this.totalAmount = totalAmount;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoice")
//	public Vector<PatientCheckin> getPatientCheckins() {
//		return this.patientCheckins;
//	}
//
//	public void setPatientCheckins(Vector<PatientCheckin> patientCheckins) {
//		this.patientCheckins = patientCheckins;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoice")
//	public Vector<Invoiceitem> getInvoiceitems() {
//		return this.invoiceitems;
//	}
//
//	public void setInvoiceitems(Vector<Invoiceitem> invoiceitems) {
//		this.invoiceitems = invoiceitems;
//	}

}
