package com.techstomach.justdental.model.schema;
// Generated Jan 4, 2017 9:42:35 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Invoiceitem generated by hbm2java
 */
@Entity
@Table(name = "invoiceitem")
public class Invoiceitem implements java.io.Serializable {

	private InvoiceitemId id;
	private Invoice invoice;
	private int serviceId;

	public Invoiceitem() {
	}

	public Invoiceitem(InvoiceitemId id, Invoice invoice, int serviceId) {
		this.id = id;
		this.invoice = invoice;
		this.serviceId = serviceId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "invoiceItemId", column = @Column(name = "InvoiceItemID", nullable = false)),
			@AttributeOverride(name = "invoiceId", column = @Column(name = "InvoiceID", nullable = false)) })
	public InvoiceitemId getId() {
		return this.id;
	}

	public void setId(InvoiceitemId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "InvoiceID", nullable = false, insertable = false, updatable = false)
	public Invoice getInvoice() {
		return this.invoice;
	}

	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	}

	@Column(name = "ServiceID", nullable = false)
	public int getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(int serviceId) {
		this.serviceId = serviceId;
	}

}
