package com.techstomach.justdental.model.schema;
// Generated Nov 19, 2016 4:08:03 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LocationDb generated by hbm2java
 */
@Entity
@Table(name = "location_db", catalog = "jd_database")
public class LocationDb implements java.io.Serializable {

	private Integer locationId;
	private String department;
	private String roomNumber;
	private boolean isActive;
	private List<SurgeryDb> surgeryDbs;
	private List<PatientCheckinDb> patientCheckinDbs;

	public LocationDb() {
	}

	public LocationDb(String department, boolean isActive) {
		this.department = department;
		this.isActive = isActive;
	}

	public LocationDb(String department, String roomNumber, boolean isActive,
					  List<SurgeryDb>  surgeryDbs, List<PatientCheckinDb> patientCheckinDbs) {
		this.department = department;
		this.roomNumber = roomNumber;
		this.isActive = isActive;
		this.surgeryDbs = surgeryDbs;
		this.patientCheckinDbs = patientCheckinDbs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "LocationID", unique = true, nullable = false)
	public Integer getLocationId() {
		return this.locationId;
	}

	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	@Column(name = "Department", nullable = false, length = 20)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "RoomNumber", length = 15)
	public String getRoomNumber() {
		return this.roomNumber;
	}

	public void setRoomNumber(String roomNumber) {
		this.roomNumber = roomNumber;
	}

	@Column(name = "IsActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locationDb")
	public List<SurgeryDb>  getSurgeryDbs() {
		return this.surgeryDbs;
	}

	public void setSurgeryDbs(List<SurgeryDb>  surgeryDbs) {
		this.surgeryDbs = surgeryDbs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locationDb")
	public List<PatientCheckinDb> getPatientCheckinDbs() {
		return this.patientCheckinDbs;
	}

	public void setPatientCheckinDbs(List<PatientCheckinDb> patientCheckinDbs) {
		this.patientCheckinDbs = patientCheckinDbs;
	}

}
