package com.techstomach.justdental.model.schema;
// Generated Dec 22, 2016 7:02:04 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import java.util.Vector;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "location")
public class Location implements java.io.Serializable {

	private int addressId;
	private int street1;
	private int street2;
	private int locality;
	private int city;
	private int state;
	private int country;
	private int gmap;
	private int isActive;
//	private Vector<Clinic> clinics = new Vector<Clinic>();
//	private Vector<Patient> patients = new Vector<Patient>();
//	private Vector<User> users = new Vector<User>();

	public Location() {
	}

	public Location(int addressId, int street1, int street2, int locality, int city, int state, int country, int gmap,
			int isActive) {
		this.addressId = addressId;
		this.street1 = street1;
		this.street2 = street2;
		this.locality = locality;
		this.city = city;
		this.state = state;
		this.country = country;
		this.gmap = gmap;
		this.isActive = isActive;
	}

//	public Location(int addressId, int street1, int street2, int locality, int city, int state, int country, int gmap,
//			int isActive,
//					Vector<Clinic> clinics, Vector<Patient> patients, Vector<User> users) {
//		this.addressId = addressId;
//		this.street1 = street1;
//		this.street2 = street2;
//		this.locality = locality;
//		this.city = city;
//		this.state = state;
//		this.country = country;
//		this.gmap = gmap;
//		this.isActive = isActive;
//		this.clinics = clinics;
//		this.patients = patients;
//		this.users = users;
//	}

	@Id

	@Column(name = "AddressID", unique = true, nullable = false)
	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	@Column(name = "Street1", nullable = false)
	public int getStreet1() {
		return this.street1;
	}

	public void setStreet1(int street1) {
		this.street1 = street1;
	}

	@Column(name = "Street2", nullable = false)
	public int getStreet2() {
		return this.street2;
	}

	public void setStreet2(int street2) {
		this.street2 = street2;
	}

	@Column(name = "Locality", nullable = false)
	public int getLocality() {
		return this.locality;
	}

	public void setLocality(int locality) {
		this.locality = locality;
	}

	@Column(name = "City", nullable = false)
	public int getCity() {
		return this.city;
	}

	public void setCity(int city) {
		this.city = city;
	}

	@Column(name = "State", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@Column(name = "Country", nullable = false)
	public int getCountry() {
		return this.country;
	}

	public void setCountry(int country) {
		this.country = country;
	}

	@Column(name = "GMAP", nullable = false)
	public int getGmap() {
		return this.gmap;
	}

	public void setGmap(int gmap) {
		this.gmap = gmap;
	}

	@Column(name = "IsActive", nullable = false)
	public int getIsActive() {
		return this.isActive;
	}

	public void setIsActive(int isActive) {
		this.isActive = isActive;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
//	public Vector<Clinic> getClinics() {
//		return this.clinics;
//	}
//
//	public void setClinics(Vector<Clinic> clinics) {
//		this.clinics = clinics;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
//	public Vector<Patient> getPatients() {
//		return this.patients;
//	}
//
//	public void setPatients(Vector<Patient> patients) {
//		this.patients = patients;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
//	public Vector<User> getUsers() {
//		return this.users;
//	}
//
//	public void setUsers(Vector<User> users) {
//		this.users = users;
//	}

}
