package com.techstomach.justdental.model.schema;
// Generated Nov 19, 2016 4:08:03 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MedicationDb generated by hbm2java
 */
@Entity
@Table(name = "medication_db", catalog = "jd_database")
public class MedicationDb implements java.io.Serializable {

	private Integer medicationId;
	private String name;
	private String description;
	private boolean isActive;
	private List<PatientMedicationDb> patientMedicationDbs;

	public MedicationDb() {
	}

	public MedicationDb(String name, boolean isActive) {
		this.name = name;
		this.isActive = isActive;
	}

	public MedicationDb(String name, String description, boolean isActive, List<PatientMedicationDb> patientMedicationDbs) {
		this.name = name;
		this.description = description;
		this.isActive = isActive;
		this.patientMedicationDbs = patientMedicationDbs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MedicationID", unique = true, nullable = false)
	public Integer getMedicationId() {
		return this.medicationId;
	}

	public void setMedicationId(Integer medicationId) {
		this.medicationId = medicationId;
	}

	@Column(name = "Name", nullable = false, length = 65535)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "IsActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medicationDb")
	public List<PatientMedicationDb> getPatientMedicationDbs() {
		return this.patientMedicationDbs;
	}

	public void setPatientMedicationDbs(List<PatientMedicationDb> patientMedicationDbs) {
		this.patientMedicationDbs = patientMedicationDbs;
	}
}
