package com.techstomach.justdental.model.schema;
// Generated Nov 19, 2016 4:08:03 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NoteDb generated by hbm2java
 */
@Entity
@Table(name = "note_db", catalog = "jd_database")
public class NoteDb implements java.io.Serializable {

	private Integer noteId;
	private PatientCheckinDb patientCheckinDb;
	private UserDb userDb;
	private String title;
	private String type;
	private String body;
	private Date dateCreated;
	private Integer noteTemplateCategoryId;
	private boolean isActive;

	public NoteDb() {
	}

	public NoteDb(PatientCheckinDb patientCheckinDb, UserDb userDb, String type, String body, Date dateCreated,
			boolean isActive) {
		this.patientCheckinDb = patientCheckinDb;
		this.userDb = userDb;
		this.type = type;
		this.body = body;
		this.dateCreated = dateCreated;
		this.isActive = isActive;
	}

	public NoteDb(PatientCheckinDb patientCheckinDb, UserDb userDb, String title, String type, String body,
			Date dateCreated, Integer noteTemplateCategoryId, boolean isActive) {
		this.patientCheckinDb = patientCheckinDb;
		this.userDb = userDb;
		this.title = title;
		this.type = type;
		this.body = body;
		this.dateCreated = dateCreated;
		this.noteTemplateCategoryId = noteTemplateCategoryId;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "NoteID", unique = true, nullable = false)
	public Integer getNoteId() {
		return this.noteId;
	}

	public void setNoteId(Integer noteId) {
		this.noteId = noteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PatientCheckInID", nullable = false)
	public PatientCheckinDb getPatientCheckinDb() {
		return this.patientCheckinDb;
	}

	public void setPatientCheckinDb(PatientCheckinDb patientCheckinDb) {
		this.patientCheckinDb = patientCheckinDb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID", nullable = false)
	public UserDb getUserDb() {
		return this.userDb;
	}

	public void setUserDb(UserDb userDb) {
		this.userDb = userDb;
	}

	@Column(name = "Title", length = 30)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "Type", nullable = false, length = 20)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "Body", nullable = false)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateCreated", nullable = false, length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "NoteTemplateCategoryID")
	public Integer getNoteTemplateCategoryId() {
		return this.noteTemplateCategoryId;
	}

	public void setNoteTemplateCategoryId(Integer noteTemplateCategoryId) {
		this.noteTemplateCategoryId = noteTemplateCategoryId;
	}

	@Column(name = "IsActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

}
