package com.techstomach.justdental.model.schema;
// Generated Nov 19, 2016 4:08:03 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OutputChartDb generated by hbm2java
 */
@Entity
@Table(name = "output_chart_db", catalog = "jd_database")
public class OutputChartDb implements java.io.Serializable {

	private Integer outputChartId;
	private PatientCheckinDb patientCheckinDb;
	private Date chartTime;
	private String ngsuctionAmount;
	private String ngsuctionColor;
	private String urineAmount;
	private String stoolAmount;
	private String stoolColor;

	public OutputChartDb() {
	}

	public OutputChartDb(PatientCheckinDb patientCheckinDb, Date chartTime) {
		this.patientCheckinDb = patientCheckinDb;
		this.chartTime = chartTime;
	}

	public OutputChartDb(PatientCheckinDb patientCheckinDb, Date chartTime, String ngsuctionAmount,
			String ngsuctionColor, String urineAmount, String stoolAmount, String stoolColor) {
		this.patientCheckinDb = patientCheckinDb;
		this.chartTime = chartTime;
		this.ngsuctionAmount = ngsuctionAmount;
		this.ngsuctionColor = ngsuctionColor;
		this.urineAmount = urineAmount;
		this.stoolAmount = stoolAmount;
		this.stoolColor = stoolColor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "OutputChartID", unique = true, nullable = false)
	public Integer getOutputChartId() {
		return this.outputChartId;
	}

	public void setOutputChartId(Integer outputChartId) {
		this.outputChartId = outputChartId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PatientCheckInID", nullable = false)
	public PatientCheckinDb getPatientCheckinDb() {
		return this.patientCheckinDb;
	}

	public void setPatientCheckinDb(PatientCheckinDb patientCheckinDb) {
		this.patientCheckinDb = patientCheckinDb;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ChartTime", nullable = false, length = 19)
	public Date getChartTime() {
		return this.chartTime;
	}

	public void setChartTime(Date chartTime) {
		this.chartTime = chartTime;
	}

	@Column(name = "NGSuctionAmount", length = 20)
	public String getNgsuctionAmount() {
		return this.ngsuctionAmount;
	}

	public void setNgsuctionAmount(String ngsuctionAmount) {
		this.ngsuctionAmount = ngsuctionAmount;
	}

	@Column(name = "NGSuctionColor", length = 30)
	public String getNgsuctionColor() {
		return this.ngsuctionColor;
	}

	public void setNgsuctionColor(String ngsuctionColor) {
		this.ngsuctionColor = ngsuctionColor;
	}

	@Column(name = "UrineAmount", length = 20)
	public String getUrineAmount() {
		return this.urineAmount;
	}

	public void setUrineAmount(String urineAmount) {
		this.urineAmount = urineAmount;
	}

	@Column(name = "StoolAmount", length = 20)
	public String getStoolAmount() {
		return this.stoolAmount;
	}

	public void setStoolAmount(String stoolAmount) {
		this.stoolAmount = stoolAmount;
	}

	@Column(name = "StoolColor", length = 30)
	public String getStoolColor() {
		return this.stoolColor;
	}

	public void setStoolColor(String stoolColor) {
		this.stoolColor = stoolColor;
	}

}
