package com.techstomach.justdental.model.schema;
// Generated Jan 4, 2017 9:42:35 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Patientdiagnosis generated by hbm2java
 */
@Entity
@Table(name = "patientdiagnosis")
public class Patientdiagnosis implements java.io.Serializable {

	private Integer patientDiagnosisId;
	private PatientMedication patientMedication;
	private Problem problem;
	private int patientId;
	private String notes;

	public Patientdiagnosis() {
	}

	public Patientdiagnosis(PatientMedication patientMedication, Problem problem, int patientId) {
		this.patientMedication = patientMedication;
		this.problem = problem;
		this.patientId = patientId;
	}

	public Patientdiagnosis(PatientMedication patientMedication, Problem problem, int patientId, String notes) {
		this.patientMedication = patientMedication;
		this.problem = problem;
		this.patientId = patientId;
		this.notes = notes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PatientDiagnosisID", unique = true, nullable = false)
	public Integer getPatientDiagnosisId() {
		return this.patientDiagnosisId;
	}

	public void setPatientDiagnosisId(Integer patientDiagnosisId) {
		this.patientDiagnosisId = patientDiagnosisId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PatientMedicationID", nullable = false)
	public PatientMedication getPatientMedication() {
		return this.patientMedication;
	}

	public void setPatientMedication(PatientMedication patientMedication) {
		this.patientMedication = patientMedication;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProblemID", nullable = false)
	public Problem getProblem() {
		return this.problem;
	}

	public void setProblem(Problem problem) {
		this.problem = problem;
	}

	@Column(name = "PatientID", nullable = false)
	public int getPatientId() {
		return this.patientId;
	}

	public void setPatientId(int patientId) {
		this.patientId = patientId;
	}

	@Column(name = "Notes")
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
