package com.techstomach.justdental.model.schema;
// Generated Jan 4, 2017 9:42:35 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.Vector;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PatientMedication generated by hbm2java
 */
@Entity
@Table(name = "patient_medication")
public class PatientMedication implements java.io.Serializable {

	private Integer patientMedicationId;
	private PatientCheckin patientCheckin;
	private String instruction;
	private Date startDate;
	private Date expDate;
	private int patientId;
//	private Vector<Patientdiagnosis> patientdiagnosises = new Vector<Patientdiagnosis>();

	public PatientMedication() {
	}

	public PatientMedication(PatientCheckin patientCheckin, String instruction, Date startDate, Date expDate,
			int patientId) {
		this.patientCheckin = patientCheckin;
		this.instruction = instruction;
		this.startDate = startDate;
		this.expDate = expDate;
		this.patientId = patientId;
	}

//	public PatientMedication(PatientCheckin patientCheckin, String instruction, Date startDate, Date expDate,
//			int patientId, Vector<Patientdiagnosis> patientdiagnosises) {
//		this.patientCheckin = patientCheckin;
//		this.instruction = instruction;
//		this.startDate = startDate;
//		this.expDate = expDate;
//		this.patientId = patientId;
//		this.patientdiagnosises = patientdiagnosises;
//	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PatientMedicationID", unique = true, nullable = false)
	public Integer getPatientMedicationId() {
		return this.patientMedicationId;
	}

	public void setPatientMedicationId(Integer patientMedicationId) {
		this.patientMedicationId = patientMedicationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PatientCheckInID", nullable = false)
	public PatientCheckin getPatientCheckin() {
		return this.patientCheckin;
	}

	public void setPatientCheckin(PatientCheckin patientCheckin) {
		this.patientCheckin = patientCheckin;
	}

	@Column(name = "Instruction", nullable = false)
	public String getInstruction() {
		return this.instruction;
	}

	public void setInstruction(String instruction) {
		this.instruction = instruction;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StartDate", nullable = false, length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ExpDate", nullable = false, length = 19)
	public Date getExpDate() {
		return this.expDate;
	}

	public void setExpDate(Date expDate) {
		this.expDate = expDate;
	}

	@Column(name = "PatientID", nullable = false)
	public int getPatientId() {
		return this.patientId;
	}

	public void setPatientId(int patientId) {
		this.patientId = patientId;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patientMedication")
//	public Vector<Patientdiagnosis> getPatientdiagnosises() {
//		return this.patientdiagnosises;
//	}
//
//	public void setPatientdiagnosises(Vector<Patientdiagnosis> patientdiagnosises) {
//		this.patientdiagnosises = patientdiagnosises;
//	}

}
