package com.techstomach.justdental.model.schema;
// Generated Nov 19, 2016 4:08:03 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PatientProblemDb generated by hbm2java
 */
@Entity
@Table(name = "patient_problem_db", catalog = "jd_database")
public class PatientProblemDb implements java.io.Serializable {

	private Integer patientProblemId;
	private PatientDb patientDb;
	private ProblemDb problemDb;

	public PatientProblemDb() {
	}

	public PatientProblemDb(PatientDb patientDb, ProblemDb problemDb) {
		this.patientDb = patientDb;
		this.problemDb = problemDb;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PatientProblemID", unique = true, nullable = false)
	public Integer getPatientProblemId() {
		return this.patientProblemId;
	}

	public void setPatientProblemId(Integer patientProblemId) {
		this.patientProblemId = patientProblemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PatientID", nullable = false)
	public PatientDb getPatientDb() {
		return this.patientDb;
	}

	public void setPatientDb(PatientDb patientDb) {
		this.patientDb = patientDb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProblemID", nullable = false)
	public ProblemDb getProblemDb() {
		return this.problemDb;
	}

	public void setProblemDb(ProblemDb problemDb) {
		this.problemDb = problemDb;
	}

}
