package com.techstomach.justdental.model.schema;
// Generated Nov 19, 2016 4:08:03 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PatientAllergyDb generated by hbm2java
 */
@Entity
@Table(name = "patient_allergy_db", catalog = "jd_database")
public class PatientAllergyDb implements java.io.Serializable {

	private Integer patientAllergyId;
	private AllergyDb allergyDb;
	private PatientDb patientDb;

	public PatientAllergyDb() {
	}

	public PatientAllergyDb(AllergyDb allergyDb, PatientDb patientDb) {
		this.allergyDb = allergyDb;
		this.patientDb = patientDb;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PatientAllergyID", unique = true, nullable = false)
	public Integer getPatientAllergyId() {
		return this.patientAllergyId;
	}

	public void setPatientAllergyId(Integer patientAllergyId) {
		this.patientAllergyId = patientAllergyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AllergyID", nullable = false)
	public AllergyDb getAllergyDb() {
		return this.allergyDb;
	}

	public void setAllergyDb(AllergyDb allergyDb) {
		this.allergyDb = allergyDb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PatientID", nullable = false)
	public PatientDb getPatientDb() {
		return this.patientDb;
	}

	public void setPatientDb(PatientDb patientDb) {
		this.patientDb = patientDb;
	}

}
