package com.techstomach.justdental.model.schema;
// Generated Nov 19, 2016 4:08:03 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PatientMedicationDb generated by hbm2java
 */
@Entity
@Table(name = "patient_medication_db", catalog = "jd_database")
public class PatientMedicationDb implements java.io.Serializable {

	private Integer patientMedicationId;
	private MedicationDb medicationDb;
	private PatientDb patientDb;
	private String instruction;
	private Date startDate;
	private Date expDate;
	private String dose;
	private String frequency;
	private int administration;

	public PatientMedicationDb() {
	}

	public PatientMedicationDb(MedicationDb medicationDb, PatientDb patientDb, Date startDate, Date expDate,
			String dose, String frequency, int administration) {
		this.medicationDb = medicationDb;
		this.patientDb = patientDb;
		this.startDate = startDate;
		this.expDate = expDate;
		this.dose = dose;
		this.frequency = frequency;
		this.administration = administration;
	}

	public PatientMedicationDb(MedicationDb medicationDb, PatientDb patientDb, String instruction, Date startDate,
			Date expDate, String dose, String frequency, int administration) {
		this.medicationDb = medicationDb;
		this.patientDb = patientDb;
		this.instruction = instruction;
		this.startDate = startDate;
		this.expDate = expDate;
		this.dose = dose;
		this.frequency = frequency;
		this.administration = administration;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PatientMedicationID", unique = true, nullable = false)
	public Integer getPatientMedicationId() {
		return this.patientMedicationId;
	}

	public void setPatientMedicationId(Integer patientMedicationId) {
		this.patientMedicationId = patientMedicationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MedicationID", nullable = false)
	public MedicationDb getMedicationDb() {
		return this.medicationDb;
	}

	public void setMedicationDb(MedicationDb medicationDb) {
		this.medicationDb = medicationDb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PatientID", nullable = false)
	public PatientDb getPatientDb() {
		return this.patientDb;
	}

	public void setPatientDb(PatientDb patientDb) {
		this.patientDb = patientDb;
	}

	@Column(name = "Instruction", length = 65535)
	public String getInstruction() {
		return this.instruction;
	}

	public void setInstruction(String instruction) {
		this.instruction = instruction;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StartDate", nullable = false, length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ExpDate", nullable = false, length = 19)
	public Date getExpDate() {
		return this.expDate;
	}

	public void setExpDate(Date expDate) {
		this.expDate = expDate;
	}

	@Column(name = "Dose", nullable = false, length = 15)
	public String getDose() {
		return this.dose;
	}

	public void setDose(String dose) {
		this.dose = dose;
	}

	@Column(name = "Frequency", nullable = false, length = 20)
	public String getFrequency() {
		return this.frequency;
	}

	public void setFrequency(String frequency) {
		this.frequency = frequency;
	}

	@Column(name = "Administration", nullable = false)
	public int getAdministration() {
		return this.administration;
	}

	public void setAdministration(int administration) {
		this.administration = administration;
	}

}
