package com.techstomach.justdental.model.schema;
// Generated Nov 19, 2016 4:08:03 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaymentDb generated by hbm2java
 */
@Entity
@Table(name = "payment_db", catalog = "jd_database")
public class PaymentDb implements java.io.Serializable {

	private Integer paymentId;
	private InvoiceDb invoiceDb;
	private BigDecimal cashAmount;
	private Date paymentDate;
	private boolean isActive;

	public PaymentDb() {
	}

	public PaymentDb(InvoiceDb invoiceDb, BigDecimal cashAmount, Date paymentDate, boolean isActive) {
		this.invoiceDb = invoiceDb;
		this.cashAmount = cashAmount;
		this.paymentDate = paymentDate;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PaymentID", unique = true, nullable = false)
	public Integer getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "InvoiceID", nullable = false)
	public InvoiceDb getInvoiceDb() {
		return this.invoiceDb;
	}

	public void setInvoiceDb(InvoiceDb invoiceDb) {
		this.invoiceDb = invoiceDb;
	}

	@Column(name = "CashAmount", nullable = false, precision = 6)
	public BigDecimal getCashAmount() {
		return this.cashAmount;
	}

	public void setCashAmount(BigDecimal cashAmount) {
		this.cashAmount = cashAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PaymentDate", nullable = false, length = 19)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Column(name = "IsActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

}
