package com.techstomach.justdental.model.schema;
// Generated Nov 19, 2016 4:08:03 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProblemDb generated by hbm2java
 */
@Entity
@Table(name = "problem_db", catalog = "jd_database")
public class ProblemDb implements java.io.Serializable {

	private Integer problemId;
	private String problemName;
	private List<PatientProblemDb> patientProblemDbs;

	public ProblemDb() {
	}

	public ProblemDb(String problemName) {
		this.problemName = problemName;
	}

	public ProblemDb(String problemName, List<PatientProblemDb> patientProblemDbs) {
		this.problemName = problemName;
		this.patientProblemDbs = patientProblemDbs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ProblemID", unique = true, nullable = false)
	public Integer getProblemId() {
		return this.problemId;
	}

	public void setProblemId(Integer problemId) {
		this.problemId = problemId;
	}

	@Column(name = "ProblemName", nullable = false, length = 30)
	public String getProblemName() {
		return this.problemName;
	}

	public void setProblemName(String problemName) {
		this.problemName = problemName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "problemDb")
	public List<PatientProblemDb> getPatientProblemDbs() {
		return this.patientProblemDbs;
	}

	public void setPatientProblemDbs(List<PatientProblemDb> patientProblemDbs) {
		this.patientProblemDbs = patientProblemDbs;
	}

}
