package com.techstomach.justdental.model.schema;
// Generated Nov 19, 2016 4:08:03 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductDb generated by hbm2java
 */
@Entity
@Table(name = "product_db", catalog = "jd_database")
public class ProductDb implements java.io.Serializable {

	private Integer productId;
	private CategoryDb categoryDb;
	private String name;
	private String unit;
	private BigDecimal productCost;
	private int quantityOnHand;
	private int counter;
	private boolean isActive;
	private List<InvoiceitemDb> invoiceitemDbs;

	public ProductDb() {
	}

	public ProductDb(CategoryDb categoryDb, String name, String unit, BigDecimal productCost, int quantityOnHand,
			int counter, boolean isActive) {
		this.categoryDb = categoryDb;
		this.name = name;
		this.unit = unit;
		this.productCost = productCost;
		this.quantityOnHand = quantityOnHand;
		this.counter = counter;
		this.isActive = isActive;
	}

	public ProductDb(CategoryDb categoryDb, String name, String unit, BigDecimal productCost, int quantityOnHand,
			int counter, boolean isActive, List<InvoiceitemDb>  invoiceitemDbs) {
		this.categoryDb = categoryDb;
		this.name = name;
		this.unit = unit;
		this.productCost = productCost;
		this.quantityOnHand = quantityOnHand;
		this.counter = counter;
		this.isActive = isActive;
		this.invoiceitemDbs = invoiceitemDbs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ProductID", unique = true, nullable = false)
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CategoryID", nullable = false)
	public CategoryDb getCategoryDb() {
		return this.categoryDb;
	}

	public void setCategoryDb(CategoryDb categoryDb) {
		this.categoryDb = categoryDb;
	}

	@Column(name = "Name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Unit", nullable = false, length = 10)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "ProductCost", nullable = false, precision = 6)
	public BigDecimal getProductCost() {
		return this.productCost;
	}

	public void setProductCost(BigDecimal productCost) {
		this.productCost = productCost;
	}

	@Column(name = "QuantityOnHand", nullable = false)
	public int getQuantityOnHand() {
		return this.quantityOnHand;
	}

	public void setQuantityOnHand(int quantityOnHand) {
		this.quantityOnHand = quantityOnHand;
	}

	@Column(name = "Counter", nullable = false)
	public int getCounter() {
		return this.counter;
	}

	public void setCounter(int counter) {
		this.counter = counter;
	}

	@Column(name = "IsActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productDb")
	public List<InvoiceitemDb>  getInvoiceitemDbs() {
		return this.invoiceitemDbs;
	}

	public void setInvoiceitemDbs(List<InvoiceitemDb>  invoiceitemDbs) {
		this.invoiceitemDbs = invoiceitemDbs;
	}

}
