package com.techstomach.justdental.model.schema;
// Generated Jan 4, 2017 9:42:35 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Service generated by hbm2java
 */
@Entity
@Table(name = "service")
public class Service implements java.io.Serializable {

	private Integer serviceId;
	private String serviceName;
	private float cost;
	private String serviceDescription;

	public Service() {
	}

	public Service(String serviceName, float cost, String serviceDescription) {
		this.serviceName = serviceName;
		this.cost = cost;
		this.serviceDescription = serviceDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ServiceID", unique = true, nullable = false)
	public Integer getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(Integer serviceId) {
		this.serviceId = serviceId;
	}

	@Column(name = "ServiceName", nullable = false)
	public String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	@Column(name = "Cost", nullable = false, precision = 14)
	public float getCost() {
		return this.cost;
	}

	public void setCost(float cost) {
		this.cost = cost;
	}

	@Column(name = "ServiceDescription", nullable = false)
	public String getServiceDescription() {
		return this.serviceDescription;
	}

	public void setServiceDescription(String serviceDescription) {
		this.serviceDescription = serviceDescription;
	}

}
