package com.techstomach.justdental.model.schema;
// Generated Nov 19, 2016 4:08:03 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SurgeryStaffDb generated by hbm2java
 */
@Entity
@Table(name = "surgery_staff_db", catalog = "jd_database")
public class SurgeryStaffDb implements java.io.Serializable {

	private Integer surgeryStaffId;
	private SurgeryDb surgeryDb;
	private UserDb userDb;
	private int role;

	public SurgeryStaffDb() {
	}

	public SurgeryStaffDb(SurgeryDb surgeryDb, UserDb userDb, int role) {
		this.surgeryDb = surgeryDb;
		this.userDb = userDb;
		this.role = role;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SurgeryStaffID", unique = true, nullable = false)
	public Integer getSurgeryStaffId() {
		return this.surgeryStaffId;
	}

	public void setSurgeryStaffId(Integer surgeryStaffId) {
		this.surgeryStaffId = surgeryStaffId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SurgeryID", nullable = false)
	public SurgeryDb getSurgeryDb() {
		return this.surgeryDb;
	}

	public void setSurgeryDb(SurgeryDb surgeryDb) {
		this.surgeryDb = surgeryDb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID", nullable = false)
	public UserDb getUserDb() {
		return this.userDb;
	}

	public void setUserDb(UserDb userDb) {
		this.userDb = userDb;
	}

	@Column(name = "Role", nullable = false)
	public int getRole() {
		return this.role;
	}

	public void setRole(int role) {
		this.role = role;
	}

}
