package com.techstomach.justdental.model.schema;
// Generated Nov 19, 2016 4:08:03 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TemplateDb generated by hbm2java
 */
@Entity
@Table(name = "template_db", catalog = "jd_database")
public class TemplateDb implements java.io.Serializable {

	private Integer templateId;
	private NoteTemplateCategoryDb noteTemplateCategoryDb;
	private UserDb userDb;
	private String title;
	private String templateBody;
	private boolean isActive;

	public TemplateDb() {
	}

	public TemplateDb(NoteTemplateCategoryDb noteTemplateCategoryDb, UserDb userDb, String title, String templateBody,
			boolean isActive) {
		this.noteTemplateCategoryDb = noteTemplateCategoryDb;
		this.userDb = userDb;
		this.title = title;
		this.templateBody = templateBody;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TemplateID", unique = true, nullable = false)
	public Integer getTemplateId() {
		return this.templateId;
	}

	public void setTemplateId(Integer templateId) {
		this.templateId = templateId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NoteTemplateCategoryID", nullable = false)
	public NoteTemplateCategoryDb getNoteTemplateCategoryDb() {
		return this.noteTemplateCategoryDb;
	}

	public void setNoteTemplateCategoryDb(NoteTemplateCategoryDb noteTemplateCategoryDb) {
		this.noteTemplateCategoryDb = noteTemplateCategoryDb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID", nullable = false)
	public UserDb getUserDb() {
		return this.userDb;
	}

	public void setUserDb(UserDb userDb) {
		this.userDb = userDb;
	}

	@Column(name = "Title", nullable = false, length = 150)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "TemplateBody", nullable = false)
	public String getTemplateBody() {
		return this.templateBody;
	}

	public void setTemplateBody(String templateBody) {
		this.templateBody = templateBody;
	}

	@Column(name = "IsActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

}
