package com.techstomach.justdental.model.schema;
// Generated Jan 4, 2017 9:42:35 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserloginId generated by hbm2java
 */
@Embeddable
public class UserloginId implements java.io.Serializable {

	private String phoneNumber;
	private String emailAddress;
	private int loginType;
	private int accessType;
	private String ipaddress;

	public UserloginId() {
	}

	public UserloginId(String phoneNumber, String emailAddress, int loginType, int accessType, String ipaddress) {
		this.phoneNumber = phoneNumber;
		this.emailAddress = emailAddress;
		this.loginType = loginType;
		this.accessType = accessType;
		this.ipaddress = ipaddress;
	}

	@Column(name = "PhoneNumber", nullable = false)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "EmailAddress", nullable = false)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "LoginType", nullable = false)
	public int getLoginType() {
		return this.loginType;
	}

	public void setLoginType(int loginType) {
		this.loginType = loginType;
	}

	@Column(name = "AccessType", nullable = false)
	public int getAccessType() {
		return this.accessType;
	}

	public void setAccessType(int accessType) {
		this.accessType = accessType;
	}

	@Column(name = "IPAddress", nullable = false)
	public String getIpaddress() {
		return this.ipaddress;
	}

	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserloginId))
			return false;
		UserloginId castOther = (UserloginId) other;

		return ((this.getPhoneNumber() == castOther.getPhoneNumber()) || (this.getPhoneNumber() != null
				&& castOther.getPhoneNumber() != null && this.getPhoneNumber().equals(castOther.getPhoneNumber())))
				&& ((this.getEmailAddress() == castOther.getEmailAddress())
						|| (this.getEmailAddress() != null && castOther.getEmailAddress() != null
								&& this.getEmailAddress().equals(castOther.getEmailAddress())))
				&& (this.getLoginType() == castOther.getLoginType())
				&& (this.getAccessType() == castOther.getAccessType())
				&& ((this.getIpaddress() == castOther.getIpaddress()) || (this.getIpaddress() != null
						&& castOther.getIpaddress() != null && this.getIpaddress().equals(castOther.getIpaddress())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPhoneNumber() == null ? 0 : this.getPhoneNumber().hashCode());
		result = 37 * result + (getEmailAddress() == null ? 0 : this.getEmailAddress().hashCode());
		result = 37 * result + this.getLoginType();
		result = 37 * result + this.getAccessType();
		result = 37 * result + (getIpaddress() == null ? 0 : this.getIpaddress().hashCode());
		return result;
	}

}
