package com.techstomach.justdental.model.schema;
// Generated Jan 4, 2017 9:42:35 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Userlogin generated by hbm2java
 */
@Entity
@Table(name = "userlogin")
public class Userlogin implements java.io.Serializable {

	private UserloginId id;

	public Userlogin() {
	}

	public Userlogin(UserloginId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "phoneNumber", column = @Column(name = "PhoneNumber", nullable = false)),
			@AttributeOverride(name = "emailAddress", column = @Column(name = "EmailAddress", nullable = false)),
			@AttributeOverride(name = "loginType", column = @Column(name = "LoginType", nullable = false)),
			@AttributeOverride(name = "accessType", column = @Column(name = "AccessType", nullable = false)),
			@AttributeOverride(name = "ipaddress", column = @Column(name = "IPAddress", nullable = false)) })
	public UserloginId getId() {
		return this.id;
	}

	public void setId(UserloginId id) {
		this.id = id;
	}

}
