package com.techstomach.justdental.model.schema;
// Generated Nov 19, 2016 4:08:03 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VitalsDb generated by hbm2java
 */
@Entity
@Table(name = "vitals_db", catalog = "jd_database")
public class VitalsDb implements java.io.Serializable {

	private Integer vitalsId;
	private PatientCheckinDb patientCheckinDb;
	private Date time;
	private boolean type;
	private Float height;
	private Float weight;
	private Integer heartRate;
	private BigDecimal temperature;
	private Integer bpsystolic;
	private Integer bpdiastolic;
	private Integer respiratoryRate;
	private boolean isActive;

	public VitalsDb() {
	}

	public VitalsDb(Date time, boolean type, boolean isActive) {
		this.time = time;
		this.type = type;
		this.isActive = isActive;
	}

	public VitalsDb(PatientCheckinDb patientCheckinDb, Date time, boolean type, Float height, Float weight,
			Integer heartRate, BigDecimal temperature, Integer bpsystolic, Integer bpdiastolic, Integer respiratoryRate,
			boolean isActive) {
		this.patientCheckinDb = patientCheckinDb;
		this.time = time;
		this.type = type;
		this.height = height;
		this.weight = weight;
		this.heartRate = heartRate;
		this.temperature = temperature;
		this.bpsystolic = bpsystolic;
		this.bpdiastolic = bpdiastolic;
		this.respiratoryRate = respiratoryRate;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "VitalsID", unique = true, nullable = false)
	public Integer getVitalsId() {
		return this.vitalsId;
	}

	public void setVitalsId(Integer vitalsId) {
		this.vitalsId = vitalsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PatientCheckInID")
	public PatientCheckinDb getPatientCheckinDb() {
		return this.patientCheckinDb;
	}

	public void setPatientCheckinDb(PatientCheckinDb patientCheckinDb) {
		this.patientCheckinDb = patientCheckinDb;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Time", nullable = false, length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "Type", nullable = false)
	public boolean isType() {
		return this.type;
	}

	public void setType(boolean type) {
		this.type = type;
	}

	@Column(name = "Height", precision = 12, scale = 0)
	public Float getHeight() {
		return this.height;
	}

	public void setHeight(Float height) {
		this.height = height;
	}

	@Column(name = "Weight", precision = 12, scale = 0)
	public Float getWeight() {
		return this.weight;
	}

	public void setWeight(Float weight) {
		this.weight = weight;
	}

	@Column(name = "HeartRate")
	public Integer getHeartRate() {
		return this.heartRate;
	}

	public void setHeartRate(Integer heartRate) {
		this.heartRate = heartRate;
	}

	@Column(name = "Temperature", precision = 4, scale = 1)
	public BigDecimal getTemperature() {
		return this.temperature;
	}

	public void setTemperature(BigDecimal temperature) {
		this.temperature = temperature;
	}

	@Column(name = "BPSystolic")
	public Integer getBpsystolic() {
		return this.bpsystolic;
	}

	public void setBpsystolic(Integer bpsystolic) {
		this.bpsystolic = bpsystolic;
	}

	@Column(name = "BPDiastolic")
	public Integer getBpdiastolic() {
		return this.bpdiastolic;
	}

	public void setBpdiastolic(Integer bpdiastolic) {
		this.bpdiastolic = bpdiastolic;
	}

	@Column(name = "RespiratoryRate")
	public Integer getRespiratoryRate() {
		return this.respiratoryRate;
	}

	public void setRespiratoryRate(Integer respiratoryRate) {
		this.respiratoryRate = respiratoryRate;
	}

	@Column(name = "IsActive", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

}
